### ISSUE TITLE
DBscorer doesn't work

### ISSUE THREAD

**Issue by piv1k** [swanandlab/DBscorer#1]
Greetings! Thank you very much for such a wonderful program! Not only does it look pretty nice but the installation of a very expensive Matlab is also not required. I installed everything according to the instructions, but I think DBscorer does not work. I upload the video, indicate the ending time and animal ID, then press the "Mark Area" button, and choose the area. When I finish the selection, Figure 2 arrives, then gone and I hear the error sound without any text or windows with error. I just see the yellow button "Cropping..." instead of "Mark Area" and nothing happens. The video icon is still uncropped. If I press other buttons, I hear the only error sound again. I tried to run DBscorrer as administrator, but it didn't help.

Could you please help me to run the program?

**Comment by NeuroRookie** [comment]
I encountered the same problem. I loaded a mp4 video, then press the "Mark Area" button. I could only see the yellow button "Cropping", and nothing happened  even after a long time.

**Comment by NeuroRookie** [comment]
DBscorer V2 didn't work before, but I retried today and it could analysis the demo video. Thanks a lot!

**Comment by NeuroRookie** [comment]
When the function worked on Matlab, it told me:
```markdown
Warning: Variable 'app' originally saved as a DBscorerV02032023 cannot be instantiated as an object and will be read in as a uint32. 
Warning: Cannot load an object of class 'DBscorerV02032023':
Its class cannot be found. 
Warning: Integer operands are required for colon operator when used as index. 
Warning: Integer operands are required for colon operator when used as index. 
Error using reshape
Size arguments must be real integers.

Error in DBscorerV02032023_exported/CompileAutoButtonPushed (line 665)
                    bin_ar = reshape(R_ar,fps,[]);

Error in appdesigner.internal.service.AppManagementService/executeCallback (line 171)
                callback(appOrUserComponent, event);

Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
            newCallback = @(source, event)executeCallback(ams, ...
 
Error using matlab.ui.control.internal.controller.ComponentController/executeUserCallback
Error while evaluating Button PrivateButtonPushedFcn.

**Comment by arnabaws** [comment]
I think the issue is frame rate. You have to convert your video to have a constant frame rate. Because of variable frame rate it is failing to reshape for binning.

**Comment by arnabaws** [comment]
Great!
