### ISSUE TITLE
AI Detection Issue: Animals Not Detected in Video

### ISSUE THREAD

**Issue by 93jun-39** [swanandlab/DBscorer#2]
I am reaching out to you with an issue I am experiencing while using the DBscorerv2 for analyzing forced swim tests in my animal study. I have been following the example video and instructions provided, but I have encountered a problem with the AI detection feature.

Upon initiating the manual scoring process, the AI detection seems to only focus on the top part of the video(as shown below), resulting in the failure to detect the animals in the video. This issue is preventing me from effectively using the program to analyze my data.

Initially, I suspected that there might be an issue with my videos. However, after testing the program with your example videos, the same situation occurs, which suggests the issue may be within the software itself.

I would greatly appreciate your assistance in resolving this issue. If you could provide any guidance on possible solutions or recommendations on how to address this problem, it would be very helpful.

![1681195221515](https://user-images.githubusercontent.com/83487232/231081654-9b463e7b-216d-4c06-9680-d3059f166cc8.jpg)

**Comment by arnabaws** [comment]
The magenta color that appears is not related to AI-detected immobility. Rather, it is intended to serve as a visual aid during manual scoring, which allows the user to change the color based on the animal's movement. If the animal is in motion, the user can change the button color to green, and when it is immobile, the color can be changed to magenta. This scoring system serves as ground truth for determining thresholds, which is achieved by analyzing a few sample videos of your data.
