### ISSUE TITLE
Issue getting threshold from manual scoring

### ISSUE THREAD

**Issue by brolinmd** [swanandlab/DBscorer#3]
Hello,

I am trying to use the Get Threshold feature to get the optimal threshold for my particular experiments. I've scored 3 videos manually and have successfully generated their .mat files. However, when I click on Get Threshold and select those .mat files, an error sound plays and no CSV file is generated. Is there something I'm not doing to generate the CSV file? Hoping to get the automatic scoring working to my liking! Thanks so much.

**Comment by BinZJU** [comment]
> Hello,
> 
> I am trying to use the Get Threshold feature to get the optimal threshold for my particular experiments. I've scored 3 videos manually and have successfully generated their .mat files. However, when I click on Get Threshold and select those .mat files, an error sound plays and no CSV file is generated. Is there something I'm not doing to generate the CSV file? Hoping to get the automatic scoring working to my liking! Thanks so much.

Hi, have you got this problem solved? Would you mind sharing the solution? I have the same issue.  Thank you.

**Comment by arnabaws** [comment]
For the question related to threshold generation first check if you can do all the steps with the provided video sample using the recommended threshold. If yes, then check if your video is converted to a constant frame rate. Even after that if it gives you error then ensure that your video has immobility between 30-70%. Sometimes it fails to compute the threshold if it doesn't have enough data. Check your file name after you generate the manual analysis; it should be in pairs, FST.mat and FST manual.mat and your video name should not contain full stop (.).

**Comment by brolinmd** [comment]
Thank you for the response! Unfortunately, I am still not able to generate optimal threshold values from my manual scoring even after implementing your suggestions. I converted the videos to constant frame rates and did not include any manual analysis where the immobility percentage was less than 30 or greater than 70. I am scoring tail suspension videos and select the TST manual.mat files for threshold detection but I am still met with an error sound and no CSV file is generated
