### ISSUE TITLE
Compile button issue

### ISSUE THREAD

**Issue by neurocook** [swanandlab/DBscorer#5]
So I can get through all the steps of DBscorer and i have the .mat files generated for all my mice, the only issue however, is that compile doesn't do anything except open an empty matlab figure window. No excel sheets are created. 

Also a side question- is it pointless to use dbscorer if my camera view angle for FST is a birds eye view instead of a side view?

**Comment by arnabaws** [comment]
Could you check if compile works  for the sample videos provided in github? Please email me a sample video of yours, I will take a look. 

Birds eye view generally are not good for most video analysis. Videos are distorted.

**Comment by Ailpo** [comment]
Hi, I'm having the same problem, I'm using the same angle as the example video, white mouse on a black background, and I can recognize the mouse accurately, is that compile doesn't do anything except open an empty matlab figure window. No excel sheets are created.

**Comment by littleleafmoon** [comment]
I have the same problem too, while there is nothing to be created after I use the compile button, except an empty figure window

**Comment by arnabaws** [comment]
Could you try by selecting > 1 mat file while compilation? If that doesn't work let me know. I am working on all issues and suggestions. Hopefully by next week I will upload.
